[project]
name = "concerto"
version = "0.1.0"
description = "Concerto is a lightweight library for asynchronous and parallel functions, aiming to assist developers in quickly writing asynchronous and parallel processes for their software."
authors = [
    {name = "David.Niteas",email = "david.ql.d@foxmail.com"}
]
license = {text = "The MIT License (MIT)"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "trio",
    "curio",
    "asyncio",
    "nest-asyncio",
    "rich",
    "uuid"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
